-- Tickets system v1
-- Safe to run multiple times.

-- For uuid generation (if not already enabled)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS tickets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_number bigint GENERATED BY DEFAULT AS IDENTITY,

  title text,
  description text NOT NULL,
  urgency text NOT NULL DEFAULT 'normal', -- normal|urgent|low (app-level enum)
  status text NOT NULL DEFAULT 'not_started', -- not_started|in_progress|resolved

  tags text[] NOT NULL DEFAULT '{}'::text[],
  reporter_email text,
  assigned_to_email text,

  attachments jsonb NOT NULL DEFAULT '[]'::jsonb,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz
);

-- Ensure ticket_number uniqueness when present
CREATE UNIQUE INDEX IF NOT EXISTS idx_tickets_ticket_number ON tickets(ticket_number);

-- Common filters
CREATE INDEX IF NOT EXISTS idx_tickets_status ON tickets(status);
CREATE INDEX IF NOT EXISTS idx_tickets_assigned_to ON tickets(assigned_to_email);
CREATE INDEX IF NOT EXISTS idx_tickets_reporter ON tickets(reporter_email);
CREATE INDEX IF NOT EXISTS idx_tickets_created_at ON tickets(created_at DESC);

-- Fast tag filtering
CREATE INDEX IF NOT EXISTS idx_tickets_tags_gin ON tickets USING gin(tags);

-- updated_at maintenance
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_tickets_set_updated_at ON tickets;
CREATE TRIGGER trg_tickets_set_updated_at
BEFORE UPDATE ON tickets
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

