"""Repository for ideas table."""
from app.database.client import get_supabase_client


class IdeaRepository:
    def __init__(self):
        self._client = get_supabase_client()

    def get_all(self):
        """Get all ideas with CS and CDI owner info."""
        return (
            self._client.table("ideas")
            .select("*, content_strategists!cs_owner_id(id, name), cdi:content_strategists!cdi_owner_id(id, name)")
            .order("idea_number", desc=True)
            .execute()
            .data
        )

    def get_by_id(self, idea_id: str):
        result = (
            self._client.table("ideas")
            .select("*, content_strategists!cs_owner_id(id, name), cdi:content_strategists!cdi_owner_id(id, name)")
            .eq("id", idea_id)
            .execute()
            .data
        )
        return result[0] if result else None

    def create(self, data: dict):
        """Create idea. idea_code is auto-generated by DB trigger."""
        return self._client.table("ideas").insert(data).execute().data[0]

    def update(self, idea_id: str, data: dict):
        return self._client.table("ideas").update(data).eq("id", idea_id).execute().data[0]

    def delete(self, idea_id: str):
        return self._client.table("ideas").delete().eq("id", idea_id).execute()


def get_idea_repository():
    return IdeaRepository()
